name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, edited ]
jobs:
  validate:
    uses: ./.github/workflows/wrapper-validation.yml

  build-lib:
    name: Build SlimJar Library
    runs-on: ubuntu-latest
    depends-on: validate
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean :slimjar:build
  build-plugin:
    name: Build SlimJar Gradle Plugin
    runs-on: ubuntu-latest
    depends-on: [build-lib validate]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: :gradle-plugin:build

  check:
    name: Run checks and tests
    runs-on: ubuntu-latest
    depends-on: [build-lib build-plugin validate]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
          arguments: :slimjar:check :gradle-plugin:check
